// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package inst

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Trivial-0]
	_ = x[Indirect-1]
	_ = x[Swap-2]
	_ = x[Compare-3]
	_ = x[NumKinds-4]
}

const _Kind_name = "TrivialIndirectSwapCompareNumKinds"

var _Kind_index = [...]uint8{0, 7, 15, 19, 26, 34}

func (i Kind) String() string {
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
